name: Migrate Repository
'on':
  workflow_dispatch: null
jobs:
  migrate:
    runs-on:
    - Standard
    - self-hosted
    - X64
    - ubuntu
    steps:
    - name: Install GEI
      run: gh extension install github/gh-gei
      env:
        GH_TOKEN: ${{ secrets.TARGET_MIGRATION_TOKEN }}
    - name: Migrate Repo
      uses: coaa/ghe-migration-scripts/migrate-repo@v1
      with:
        source_repo: theegalahub/test
        target_repo: sapthagirireddy/destrepo
        source_token: ${{ secrets.SOURCE_MIGRATION_TOKEN }}
        target_token: ${{ secrets.TARGET_MIGRATION_TOKEN }}
        visibility: public
        users_to_assign_admin: theegalahub
        users_to_assign_write: theegalahub
